import assert from 'node:assert/strict';
import { createServer } from 'vite';
import { fileURLToPath } from 'node:url';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');

const server = await createServer({root:fileURLToPath(new URL('..', import.meta.url)),server:{host:'127.0.0.1',port:5173,strictPort:true}});
await server.listen();
const browser = await chromium.launch({headless:true, executablePath:process.env.CHROMIUM_EXECUTABLE, args:JSON.parse(process.env.CHROMIUM_ARGS || '[]')});
const page=await browser.newPage({viewport:{width:1100,height:1200}});
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
page.on('dialog',d=>d.accept());
const board=async(fn,arg)=>page.evaluate(({fn,arg})=>new Function('b','arg',`return (${fn})(b,arg)`)(document.querySelector('#app').__vue_app__._instance.setupState.canvas,arg),{fn:fn.toString(),arg});
const count=async n=>page.waitForFunction(n=>document.querySelector('#app').__vue_app__._instance.setupState.canvas.getObjects().length===n,n);
const idle=()=>page.waitForFunction(()=>!document.querySelector('#app').__vue_app__._instance.setupState.canvas.getHistoryState().busy);
async function draw(x=400,y=120,dx=140,dy=40){
 const box=await page.locator('.upper-canvas').boundingBox();
 await page.mouse.move(box.x+x,box.y+y);await page.mouse.down();await page.mouse.move(box.x+x+dx,box.y+y+dy,{steps:10});await page.mouse.up();
 await page.waitForTimeout(80);
}
try {
await page.goto('http://127.0.0.1:5173/interactive-whiteboard/');
await page.waitForSelector('.upper-canvas');
assert.equal(await page.locator('.tool-mid-box-left').evaluate(el=>getComputedStyle(el).flexDirection),'column');
await page.getByRole('button',{name:'笔',exact:true}).click();
assert.equal(await page.getByRole('button',{name:'切换工具设置'}).getAttribute('aria-expanded'),'true');
await page.getByRole('button',{name:'笔',exact:true}).click();
assert.equal(await page.getByRole('button',{name:'切换工具设置'}).getAttribute('aria-expanded'),'false');
await page.getByRole('button',{name:'切换工具设置'}).click();
await page.keyboard.press('Escape');
assert.equal(await page.getByRole('button',{name:'切换工具设置'}).getAttribute('aria-expanded'),'false');
await page.getByRole('button',{name:'切换工具设置'}).click();
await page.locator('.app-header h1').click();
assert.equal(await page.getByRole('button',{name:'切换工具设置'}).getAttribute('aria-expanded'),'false');
await board(b=>b.getCanvas().upperCanvasEl.focus());
await page.keyboard.press('1');
assert.equal(await board(b=>b.getDrawingTool()),'select');
await page.keyboard.press('2');
assert.equal(await board(b=>b.getDrawingTool()),'pencil');
console.log('PASS toolbar toggles, dismissal, focused shortcuts and original layout');
assert.equal(await page.getByRole('button',{name:'切换工具设置'}).getAttribute('aria-expanded'),'true');
await page.getByRole('button',{name:'10',exact:true}).click();
await page.getByRole('button',{name:'选择颜色 #3b82f6',exact:true}).click();
assert.equal(await page.getByRole('button',{name:'撤销',exact:true}).isDisabled(),true);
await draw(); await count(1);
assert.deepEqual(await board(b=>({color:b.getObjects()[0].stroke,width:b.getObjects()[0].strokeWidth})),{color:'#3b82f6',width:10});
await page.getByRole('button',{name:'撤销',exact:true}).click();await count(0);await idle();
await page.getByRole('button',{name:'重做',exact:true}).click();await count(1);await idle();
await page.getByRole('button',{name:'撤销',exact:true}).click();await count(0);await idle();
await draw(420,220);await count(1);
assert.equal(await page.getByRole('button',{name:'重做',exact:true}).isDisabled(),true);
console.log('PASS brush settings, initial undo, redo and history branching');
await page.getByRole('button',{name:'橡皮擦',exact:true}).click();
await page.getByRole('button',{name:'40',exact:true}).click();
assert.equal(await board(b=>b.getCanvas().freeDrawingBrush.width),40);
await page.getByRole('button',{name:'笔',exact:true}).click();
assert.equal(await board(b=>b.getCanvas().freeDrawingBrush.width),10);
await page.reload();await page.waitForSelector('.upper-canvas');
assert.deepEqual(await board(b=>b.getBrushSettings()),{color:'#3b82f6',width:10,eraserWidth:40});
console.log('PASS separate eraser size and settings persistence');
await page.getByRole('button',{name:'箭头',exact:true}).click();
await draw(400,150);await count(1);
assert.equal(await board(b=>b.getObjects()[0].constructor.type),'Arrow');
await page.waitForFunction(()=>document.querySelector('#app').__vue_app__._instance.setupState.mirror.getObjects()[0]?.constructor.type==='Arrow');
await page.getByRole('button',{name:'撤销',exact:true}).click();await count(0);await idle();
await page.getByRole('button',{name:'重做',exact:true}).click();await count(1);await idle();
assert.equal(await board(b=>b.getObjects()[0].constructor.type),'Arrow');
assert.equal(await board(b=>b.getObjects()[0].erasable),true);
console.log('PASS arrow and erasable serialization in history and mirror');
await page.getByRole('button',{name:'橡皮擦',exact:true}).click();
await draw(400,150);await count(0);
await page.getByRole('button',{name:'撤销',exact:true}).click();await count(1);await idle();
console.log('PASS restored objects remain erasable');
await page.getByRole('button',{name:'选择',exact:true}).click();
await board(b=>{b.getCanvas().setActiveObject(b.getObjects()[0]);b.getCanvas().upperCanvasEl.focus();});
await page.keyboard.press('Control+c');await page.waitForTimeout(100);
await page.keyboard.press('Control+v');await count(2);
await page.keyboard.press('Control+v');await count(3);
assert.equal(await board(b=>new Set(b.getObjects()).size),3);
await page.keyboard.press('Backspace');await count(2);
await page.keyboard.press('Control+z');await count(3);await idle();
console.log('PASS independent paste, keyboard delete and undo');
await page.getByRole('button',{name:'打开示例课件',exact:true}).click();await idle();await count(0);
await page.getByRole('button',{name:'笔',exact:true}).click();await draw(400,180);await count(1);
const page1=await board(b=>JSON.stringify(b.toJSON()));
await page.getByRole('button',{name:'下一页',exact:true}).click();await idle();await count(0);
await draw(450,260);await count(1);
const page2=await board(b=>JSON.stringify(b.toJSON()));
assert.notEqual(page1,page2);
await page.getByRole('button',{name:'上一页',exact:true}).click();await idle();await count(1);
assert.equal(await board(b=>JSON.stringify(b.toJSON())),page1);
await page.getByRole('button',{name:'清除批注',exact:true}).click();await count(0);
assert.equal(await board(b=>!!b.getCanvas().backgroundImage),true);
await page.getByRole('button',{name:'撤销',exact:true}).click();await idle();await count(1);
assert.equal(await board(b=>JSON.stringify(b.toJSON())),page1);
console.log('PASS page isolation, page history and clear preserving background');
const download=page.waitForEvent('download');await page.getByRole('button',{name:'导出 PNG',exact:true}).click();
const file=await download;assert.match(file.suggestedFilename(),/\.png$/);assert.equal(await file.failure(),null);

console.log('PASS PNG export');
await page.getByRole('button',{name:'页面预览',exact:true}).click();
await page.locator('.page-box').nth(1).click();await idle();
assert.equal(await board(b=>JSON.stringify(b.toJSON())),page2);
await page.locator('.page-box-under-right').nth(1).click();await idle();
assert.equal(await board(b=>b.getScenes().length),5);
console.log('PASS thumbnail navigation and page deletion');
assert.deepEqual(errors,[]);
if (process.env.SCREENSHOT_PATH) await page.screenshot({path:process.env.SCREENSHOT_PATH,fullPage:true});
await page.evaluate(() => document.querySelector('#app').__vue_app__.unmount());
await page.waitForTimeout(100);
assert.deepEqual(errors,[]);
console.log('PASS unmount cleanup');
console.log('ALL BROWSER CHECKS PASSED');
} finally {await browser.close();await server.close();}
